import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image"; 
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light" lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/"><Image src={'/logo.png'} width={392} height={158} alt="logo" className="navLogo" /></Link>
          <div className="rightNav">
            <Link href="/day-view">Tasks</Link>
            <Link href="/dashboard">Dashboard</Link>
            <Link href="/register">Register</Link>
            <Link href="/login">Login</Link>
            <Link href="/register">Register</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
